//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chamadosDB
    {
        public int chamadoID { get; set; }
        public int usuarioID { get; set; }
        public string sistemaChamado { get; set; }
        public string descricao { get; set; }
    
        public virtual usuariosDB usuariosDB { get; set; }
    }
}
